"""Migração Inicial

Revision ID: 0505a06fb645
Revises: 
Create Date: 2024-11-22 09:17:50.180088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0505a06fb645'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paciente',
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_paciente')
    )
    op.create_table('consulta',
    sa.Column('id_consulta', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('observacoes', sa.String(length=255), nullable=True),
    sa.Column('id_paciente', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_paciente'], ['paciente.id_paciente'], ),
    sa.PrimaryKeyConstraint('id_consulta')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consulta')
    op.drop_table('paciente')
    # ### end Alembic commands ###
